import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./layout-wrapper";
import { MenuContextProvider } from "@/context/menu-context";
import { AuthProvider } from "@/context/auth-context";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider } from "@/components/ui/sidebar";
import { QueryProvider } from "@/providers/query-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable}  antialiased`}>
        <ThemeProvider>
          <QueryProvider>
            <MenuContextProvider>
              <TooltipProvider>
                <AuthProvider>
                  <SidebarProvider>
                    <LayoutWrapper>
                      {children}
                      <Toaster richColors invert />
                    </LayoutWrapper>
                  </SidebarProvider>
                </AuthProvider>
              </TooltipProvider>
            </MenuContextProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
